import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from 'next/link';
import FilterBar from "../components/FilterBar";
import BottomNav from "../components/BottomNav";
import PointsBadge from "../components/PointsBadge";


export default function RootLayout({ children }: { children: React.ReactNode }) {
  // Simulação: checar se usuário é admin (depois integrar com Supabase)
  const isAdmin = false;

  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white font-sans min-h-screen relative`}>
        {/* Header principal */}
        <header className="w-full flex flex-col md:flex-row justify-between items-center px-4 md:px-8 py-4 bg-gray-900 shadow z-20">
          <div className="flex items-center gap-4">
            <Link href="/" className="text-2xl font-extrabold text-yellow-400">RANKIOU</Link>
            {isAdmin && (
              <Link href="/admin" title="Painel Admin" className="text-xl ml-2">🛡️</Link>
            )}
          </div>
          <nav className="flex flex-wrap gap-4 md:gap-6 items-center mt-2 md:mt-0">
            <Link href="/" className="hover:text-yellow-300">Início</Link>
            <Link href="/rankards" className="hover:text-yellow-300">Rankards</Link>
            <Link href="/acompanhar" className="hover:text-yellow-300">Acompanhar</Link>
            <Link href="/como-funciona" className="hover:text-yellow-300">Como Funciona</Link>
            <Link href="/faq" className="hover:text-yellow-300">FAQ</Link>
            <Link href="/contato" className="hover:text-yellow-300">Contato</Link>
            <Link href="/criar" className="bg-yellow-400 text-black px-3 py-1 rounded font-bold hover:bg-yellow-300">Criar Enquete</Link>
            <Link href="/profile" className="hover:text-yellow-300">Perfil</Link>
            <Link href="/login" className="hover:text-yellow-300">Login</Link>
          </nav>
          {/* Ícone de pontos e notificações */}
          <div className="flex items-center gap-4 ml-4">
            <PointsBadge />
            <span className="text-xl">🔔</span>
          </div>
        </header>

        {/* Barra de filtros persistente */}
        <FilterBar />

        {/* Main content */}
        <main className="w-full max-w-4xl mx-auto py-8 px-4">
          {children}
        </main>

  {/* Navegação inferior mobile */}
  <BottomNav />

        {/* Footer */}
        <footer className="w-full text-center py-10 text-gray-400 text-sm mt-16 border-t border-gray-800">
          <div className="flex gap-6 justify-center mb-3">
            <Link href="/termos" className="hover:text-yellow-300">Termos de Uso</Link>
            <Link href="/privacidade" className="hover:text-yellow-300">Política de Privacidade</Link>
          </div>
          <div>&copy; 2025 Rankiou. Todos os direitos reservados.</div>
        </footer>
      </body>
    </html>
  );
}
