import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from 'next/link';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white font-sans min-h-screen`}>
        <header className="w-full flex justify-between items-center px-8 py-4 bg-gray-900 shadow">
          <Link href="/" className="text-2xl font-extrabold text-yellow-400">RANKIOU</Link>
          <nav className="flex gap-6">
            <Link href="/" className="hover:text-yellow-300">Início</Link>
            <Link href="/login" className="hover:text-yellow-300">Login</Link>
            <Link href="/profile" className="hover:text-yellow-300">Perfil</Link>
          </nav>
        </header>
        <main className="w-full max-w-4xl mx-auto py-8 px-4">
          {children}
        </main>
        <footer className="w-full text-center py-6 text-gray-500 text-sm mt-12">
          &copy; 2025 Rankiou. Todos os direitos reservados.
        </footer>
      </body>
    </html>
  );
}
